<a href="https://colab.research.google.com/github/humsarika/machine-learning-practice/blob/main/Time_method_for_datetime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime as dt

In [ ]:
help(dt)

Help on class datetime in module datetime:

class datetime(date)
 |  datetime(year, month, day[, hour[, minute[, second[, microsecond[,tzinfo]]]]])
 |
 |  The year, month and day arguments are required. tzinfo may be None, or an
 |  instance of a tzinfo subclass. The remaining arguments may be ints.
 |
 |  Method resolution order:
 |      datetime
 |      date
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __radd__(self, value, /)
 |      Return value+self.
 |
 |  __reduce__(...)
 |      __reduce__() -> (cls, state)
 |
 |  __reduce_ex__(...)
 |      __reduce_ex__(proto) -> (cls, state)
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rsub__(self, value, /)
 |      Return value-self.
 |
 |  __str__(self, /)
 |      Return str(self).
 |
 |  __sub__(self, value, /)
 |      Return self-value.
 |
 |  astimezone(...)
 |      tz -> convert to local time in new timezone tz
 |
 |  ctime(...)
 |      Return ctime() style string.
 |
 |  date(...)
 |      Return date object with same year, month and day.
 |
 |  dst(...)
 |      Return self.tzinfo.dst(self).
 |
 |  isoformat(...)
 |      [sep] -> string in ISO 8601 format, YYYY-MM-DDT[HH[:MM[:SS[.mmm[uuu]]]]][+HH:MM].
 |      sep is used to separate the year from the time, and defaults to 'T'.
 |      The optional argument timespec specifies the number of additional terms
 |      of the time to include. Valid options are 'auto', 'hours', 'minutes',
 |      'seconds', 'milliseconds' and 'microseconds'.
 |
 |  replace(...)
 |      Return datetime with new specified fields.
 |
 |  time(...)
 |      Return time object with same time but with tzinfo=None.
 |
 |  timestamp(...)
 |      Return POSIX timestamp as float.
 |
 |  timetuple(...)
 |      Return time tuple, compatible with time.localtime().
 |
 |  timetz(...)
 |      Return time object with same time and tzinfo.
 |
 |  tzname(...)
 |      Return self.tzinfo.tzname(self).
 |
 |  utcoffset(...)
 |      Return self.tzinfo.utcoffset(self).
 |
 |  utctimetuple(...)
 |      Return UTC time tuple, compatible with time.localtime().
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  combine(...) from builtins.type
 |      date, time -> datetime with same date and time fields
 |
 |  fromisoformat(...) from builtins.type
 |      string -> datetime from datetime.isoformat() output
 |
 |  fromtimestamp(...) from builtins.type
 |      timestamp[, tz] -> tz's local time from POSIX timestamp.
 |
 |  now(tz=None) from builtins.type
 |      Returns new datetime object representing current time local to tz.
 |
 |        tz
 |          Timezone object.
 |
 |      If no tz is specified, uses local timezone.
 |
 |  strptime(...) from builtins.type
 |      string, format -> new datetime parsed from a string (like time.strptime()).
 |
 |  utcfromtimestamp(...) from builtins.type
 |      Construct a naive UTC datetime from a POSIX timestamp.
 |
 |  utcnow(...) from builtins.type
 |      Return a new datetime representing UTC day and time.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  fold
 |
 |  hour
 |
 |  microsecond
 |
 |  minute
 |
 |  second
 |
 |  tzinfo
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  max = datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
 |
 |  min = datetime.datetime(1, 1, 1, 0, 0)
 |
 |  resolution = datetime.timedelta(microseconds=1)
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from date:
 |
 |  __format__(...)
 |      Formats self with strftime.
 |
 |  isocalendar(...)
 |      Return a named tuple containing ISO year, week number, and weekday.
 |
 |  isoweekday(...)
 |      Return the day of the week represented by the date.
 |      Monday == 1 ... Sunday == 7
 |
 |  strftime(...)
 |      format -> strftime() style string.
 |
 |  toordinal(...)
 |      Return proleptic Gregorian ordinal.  January 1 of year 1 is day 1.
 |
 |  weekday(...)
 |      Return the day of the week represented by the date.
 |      Monday == 0 ... Sunday == 6
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from date:
 |
 |  fromisocalendar(...) from builtins.type
 |      int, int, int -> Construct a date from the ISO year, week number and weekday.
 |
 |      This is the inverse of the date.isocalendar() function
 |
 |  fromordinal(...) from builtins.type
 |      int -> date corresponding to a proleptic Gregorian ordinal.
 |
 |  today(...) from builtins.type
 |      Current date or datetime:  same as self.__class__.fromtimestamp(time.time()).
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from date:
 |
 |  day
 |
 |  month
 |
 |  year

In [ ]:
myyear = 2024
mymonth= 12
myday=7
myhour = 20
myminute=40
mysecond = 10

In [ ]:
mydatetime = dt(myyear,mymonth,myday,myhour,myminute,mysecond)
mydatetime

datetime.datetime(2024, 12, 7, 20, 40, 10)

In [ ]:
mydatetime.year

2024

In [ ]:
myser = pd.Series(['Dec 12, 2024', '2001-12-22',None])
myser

0    Dec 12, 2024
1      2001-12-22
2            None
dtype: object

In [ ]:
mydateseries = pd.to_datetime(myser,format='mixed')#it will give in yyyy-mm-dd format
mydateseries

0   2024-12-12
1   2001-12-22
2          NaT
dtype: datetime64[ns]

In [ ]:
obvi_eruope_date = '31-12-2024'# dd-m-yyyy
pd.to_datetime(obvi_eruope_date)

<ipython-input-31-5b50d21a2857>:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime(obvi_eruope_date)

Timestamp('2024-12-31 00:00:00')

In [ ]:
eurodate2 = '10-12-2024' # in europe its 10th dec 2024 but in america they might think its 12th oct 2024, and pandas uses american format
pd.to_datetime(eurodate2)

Timestamp('2024-10-12 00:00:00')

In [ ]:
# to deal with this case we mention if first one is day or not
pd.to_datetime(eurodate2, dayfirst=True)

Timestamp('2024-12-10 00:00:00')

In [ ]:
style_date = '22---Dec---2001'
pd.to_datetime(style_date, format= '%d---%b---%Y') # %b because i have written mnth name in word

Timestamp('2001-12-22 00:00:00')

In [ ]:
custom_date = '22nd of december 2024' # pandas is smart enough to understand this date formt
pd.to_datetime(custom_date)

Timestamp('2024-12-22 00:00:00')

In [ ]:
beer_sales = pd.read_csv('RetailSales_BeerWineLiquor.csv')
beer_sales.head()

         DATE  MRTSSM4453USN
0  1992-01-01           1509
1  1992-02-01           1541
2  1992-03-01           1597
3  1992-04-01           1675
4  1992-05-01           1822

In [ ]:
beer_sales['DATE']

0      1992-01-01
1      1992-02-01
2      1992-03-01
3      1992-04-01
4      1992-05-01
          ...
335    2019-12-01
336    2020-01-01
337    2020-02-01
338    2020-03-01
339    2020-04-01
Name: DATE, Length: 340, dtype: object

In [ ]:
pd.to_datetime(beer_sales['DATE']) # we can do this while reading the csv file

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [ ]:
beer_sales = pd.read_csv('RetailSales_BeerWineLiquor.csv', parse_dates=[0])
beer_sales.head()

        DATE  MRTSSM4453USN
0 1992-01-01           1509
1 1992-02-01           1541
2 1992-03-01           1597
3 1992-04-01           1675
4 1992-05-01           1822

In [ ]:
# set index to date column
beer_sales = beer_sales.set_index('DATE')
beer_sales

            MRTSSM4453USN
DATE
1992-01-01           1509
1992-02-01           1541
1992-03-01           1597
1992-04-01           1675
1992-05-01           1822
...                   ...
2019-12-01           6630
2020-01-01           4388
2020-02-01           4533
2020-03-01           5562
2020-04-01           5207

[340 rows x 1 columns]

In [ ]:
beer_sales.resample(rule='A').mean() #A for grouping by Year

<ipython-input-56-c63e564d4452>:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  beer_sales.resample(rule='A').mean() #A for grouping by Year

            MRTSSM4453USN
DATE
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000

In [ ]:
beer_sales = pd.read_csv('RetailSales_BeerWineLiquor.csv', parse_dates=[0])
beer_sales.head()

        DATE  MRTSSM4453USN
0 1992-01-01           1509
1 1992-02-01           1541
2 1992-03-01           1597
3 1992-04-01           1675
4 1992-05-01           1822

In [ ]:
beer_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           340 non-null    datetime64[ns]
 1   MRTSSM4453USN  340 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 5.4 KB

In [ ]:
beer_sales['DATE'].dt.year

0      1992
1      1992
2      1992
3      1992
4      1992
       ...
335    2019
336    2020
337    2020
338    2020
339    2020
Name: DATE, Length: 340, dtype: int32